image: python:3.6

services:
  - postgres:10.5-alpine

variables:
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test
  PGDATA: /var/lib/postgresql/data

test:
  before_script:
    - pip install -r requirements/test.txt

  script:
    - python manage.py test --settings config.settings.test
