version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
      PGDATA: /var/lib/postgresql/data
    ports:
    - 5432:5432
